name: eQTLGenPopAssign
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
  - anaconda
dependencies:
  - gcc_linux-64=7.3.0
  - bioconda::tabix=0.2.6
  - bioconda::bcftools=1.10.2
  - bioconda::plink2=1.90b3.35
  - conda-forge::numpy=1.23.4
  - conda-forge::pandas=1.5.1
  - conda-forge::r-igraph=1.2.6
  - conda-forge::cairo=1.16.0
  - conda-forge::r-data.table=1.14.0
  - conda-forge::r-dplyr=1.0.7
  - conda-forge::r-ggplot2=3.3.5
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-patchwork=1.1.1
  - conda-forge::mscorefonts=0.0.1
  - conda-forge::r-rmarkdown=2.10
  - conda-forge::r-cairo=1.5_12.2
  - bioconda::bioconductor-edger=3.32.1
  - conda-forge::r-hexbin=1.28.1
  - conda-forge::r-remotes=2.4.2
